# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: meu-secret
type: Opaque
data:
  SENHA_DB: c2VuaGExMjM=  # senha123 em base64
---
# pod-com-secret.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-com-secret
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo $SENHA_DB && sleep 3600"]
    env:
    - name: SENHA_DB
      valueFrom:
        secretKeyRef:
          name: meu-secret
          key: SENHA_DB