apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-compartilhado
spec:
  volumes:
    - name: dados-compartilhados
      emptyDir: {}
  containers:
    - name: writer
      image: busybox
      command: [ "sh", "-c", "echo 'Olá do container writer!' > /dados/menssagem.txt && sleep 3600" ]
      volumeMounts:
        - name: dados-compartilhados
          mountPath: /dados
    - name: reader
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      volumeMounts:
        - name: dados-compartilhados
          mountPath: /dados