apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-container
          image: nginx:1.21
          ports:
            - containerPort: 80