apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-simples
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
        - name: hello-container
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Hello from ReplicaSet'; sleep 10; done"]